// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type User struct {
	ID   int32     `db:"id" json:"id"`
	Name string    `db:"name" json:"name"`
	Dob  time.Time `db:"dob" json:"dob"`
}
